language: java
jdk: openjdk11
before_script:
  - sleep 15
  - mongo jugoterapia --eval "db.createUser({user:'$MONGODB_USER',pwd:'$MONGODB_PASSWORD',roles:['readWrite']});"
  - mongoimport --db jugoterapia --collection category --authenticationDatabase jugoterapia --username $MONGODB_USER --password $MONGODB_PASSWORD --file 'src/main/resources/categories.json'
  - mongoimport --db jugoterapia --collection beverage --authenticationDatabase jugoterapia --username $MONGODB_USER --password $MONGODB_PASSWORD --file 'src/main/resources/beverages.json'
services:
  - mongodb
script:
  - ./gradlew test jacocoTestReport sonarqube -Dspring.data.mongodb.username=$MONGODB_USER -Dspring.data.mongodb.password=$MONGODB_PASSWORD
