language: java
jdk: openjdk8
before_script:
  - sleep 15
  - mongo jugoterapia --eval "db.createUser({user:'$MONGODB_USER',pwd:'$MONGODB_PASSWORD',roles:['readWrite']});"
  - mongoimport --db jugoterapia --collection category --authenticationDatabase jugoterapia --username jugoterapiaUser --password jug0t3r4p14DB --file 'src/main/resources/categories.json'
  - mongoimport --db jugoterapia --collection beverage --authenticationDatabase jugoterapia --username jugoterapiaUser --password jug0t3r4p14DB --file 'src/main/resources/beverages.json'
services:
  - mongodb
script:
  - ./gradlew test jacocoTestReport sonarqube
